test-requirements.txt: Add six>0.11
coala/coala-ls pull request #6
Opened 2018-06-06 04:36 UTC by jayvdb

Fixes #5

2018-06-06 05:02 UTC, jayvdb commented
I've also raised https://github.com/behave/behave/pull/663 to have Python 3.4 re-added to their build matrix so they might see such problems before we do.

2018-06-06 05:23 UTC, ksdme requested changes

2018-06-06 05:23 UTC, ksdme commented on requirements.txt
> +codecov
```test-requirements.txt``` already contains the required testing dependencies. I think these should be dropped.

2018-06-06 19:00 UTC, ksdme approved these changes

2018-06-07 02:45 UTC, gaocegege approved these changes
LGTM

2018-06-07 02:51 UTC, gaocegege commented
@gitmate-bot rebase

2018-06-07 02:53 UTC, gaocegege commented
ack 21c4c990e760491426b68c2f2119dbe56bc45a63 a8baa6dbc27d24f4fd27f7c8414bced0fd700975

2018-06-07 02:56 UTC, gaocegege commented
@gitmate-bot ff

2018-06-07 03:21 UTC, jayvdb commented
@gitmate-bot ff

2018-06-07 03:30 UTC, jayvdb commented
looks like gitmate is busted on this repo.

2018-06-07 03:31 UTC, merged

2018-06-07 03:32 UTC, jayvdb commented
Did it the manual way